export const shoes = {
    data : [
        {   

            id: "1",
            title : "Nike Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/uirypqqxq83mwcjbf9ej/air-monarch-iv-training-shoe-cc3XbD.png",
            price : 5299,
            for :"men",     
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "nike",
        },
        {   
            id: "2",
            title : "Nike Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/uirypqqxq83mwcjbf9ej/air-monarch-iv-training-shoe-cc3XbD.png",
            price : 5299,
            for :"men",     
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "nike",
        },
        {   
            id: "3",
            title : "Nike Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/uirypqqxq83mwcjbf9ej/air-monarch-iv-training-shoe-cc3XbD.png",
            price : 5299,
            for :"men",  
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "nike",

        },
        {   
            id: "4",
            title : "Nike Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/uirypqqxq83mwcjbf9ej/air-monarch-iv-training-shoe-cc3XbD.png",
            price : 5299,
            for :"men",     
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "nike",

        },
        {   
            id: "5",
            title : "Nike Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/uirypqqxq83mwcjbf9ej/air-monarch-iv-training-shoe-cc3XbD.png",
            price : 5299,
            for :"men",  
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "nike",

        },
        {   
            id: "6",
            title : "Nike Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"women",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "nike",
        },
        {   
            id: "7",
            title : "Nike Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"women",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "nike",
        },
        {   
            id: "8",
            title : "Nike Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"women",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "nike",
        },
        {   
            id: "9",
            title : "Nike Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"women",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "nike",
        },
        {   
            id: "10",
            title : "Nike Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"women",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "nike",
        },
        {   
            id: "11",
            title : "Adidas Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"men",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "adidas",
        },
        {   
            id: "12",
            title : "Adidas Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"men",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "adidas",
        },
        {   
            id: "13",
            title : "Adidas Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"men",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "adidas",
        },
        {   
            id: "14",
            title : "Adidas Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"men",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "adidas",
        },
        {   
            id: "15",
            title : "Adidas Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"men",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "adidas",
        },
        {   
            id: "16",
            title : "Adidas Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"women",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "adidas",
        },
        {   
            id: "17",
            title : "Adidas Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"women",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "adidas",
        },
        {   
            id: "18",
            title : "Adidas Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"women",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "adidas",
        },
        {   
            id: "19",
            title : "Adidas Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"women",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "adidas",
        },
        {   
            id: "20",
            title : "Adidas Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"women",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "adidas",
        },
        {   
            id: "21",
            title : "Adidas Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"men",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "puma",
        },
        {   
            id: "22",
            title : "Adidas Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"men",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "puma",
        },
        {   
            id: "23",
            title : "Adidas Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"men",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "puma",
        },
        {   
            id: "24",
            title : "Adidas Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"men",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "puma",
        },
        {   
            id: "25",
            title : "Adidas Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"men",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "puma",
        },
        {   
            id: "26",
            title : "Adidas Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"women",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "puma",
        },
        {   
            id: "27",
            title : "Adidas Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"women",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "puma",
        },
        {   
            id: "28",
            title : "Adidas Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"women",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "puma",
        },
        {   
            id: "29",
            title : "Adidas Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"women",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "puma",
        },
        {   
            id: "30",
            title : "Adidas Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"women",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "puma",
        },
        {   
            id: "31",
            title : "Adidas Air Monarch IV sets you up for working out with durable leather on top for support. Lightweight foam teams up with Nike Air cushioning for comfort in every stride.",
            img : "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd84dd66-a06c-4bb1-b324-cd8a1bbf8ed6/air-jordan-1-low-se-shoes-1qN4j5.png",
            price : 5299,
            for :"women",
            des : "The one and only Air Jordan 1 Low gets a new look and feel with this special utility edition.It's made from rugged, black and white canvas material, including the Swoosh logo.Red stitch detail adds a pop of colour along the overlays." ,    
            brand : "puma",
        },

    ]
}